# Generated by Django 4.1.7 on 2023-04-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acompanhante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Nome do acompanhante", max_length=30),
                ),
                (
                    "sobrenome",
                    models.CharField(
                        help_text="Sobrenome do acompanhante", max_length=200
                    ),
                ),
            ],
        ),
    ]
