# Generated by Django 4.1.1 on 2023-04-01 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_remove_paciente_acompanhante"),
        ("acompanhantes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="acompanhante",
            name="paciente_acompanhado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pacientes.paciente",
            ),
            preserve_default=False,
        ),
    ]
