# Generated by Django 4.1.7 on 2023-03-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do jogo', max_length=100)),
                ('genero', models.CharField(help_text='Genero do jogo. Ex: ação', max_length=100)),
                ('ano', models.DateTimeField(help_text='Ano de lançamento', verbose_name='%YYYY')),
                ('preco', models.DecimalField(decimal_places=2, help_text='preço do jogo', max_digits=5)),
            ],
        ),
    ]
