# Generated by Django 4.1.7 on 2023-03-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogame_store', '0002_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='ano',
            field=models.DateField(help_text='Ano de lançamento', verbose_name='%YYYY'),
        ),
    ]
