# Generated by Django 4.1.7 on 2023-03-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogame_store', '0003_alter_jogo_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='ano',
            field=models.CharField(help_text='Ano de lançamento', max_length=4),
        ),
    ]
