# Generated by Django 4.1.7 on 2023-04-01 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("acompanhantes", "0001_initial"),
        ("medicos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Nome do funcionario", max_length=30),
                ),
                (
                    "sobrenome",
                    models.CharField(
                        help_text="Sobrenomes do funcionario", max_length=200
                    ),
                ),
                (
                    "idade",
                    models.IntegerField(
                        help_text="Idade do funcionário (apenas numeros)"
                    ),
                ),
                ("sexo", models.CharField(help_text="Sexo: M ou F", max_length=1)),
                (
                    "alergias",
                    models.CharField(help_text="Alergias do paciente", max_length=500),
                ),
                (
                    "tipo_sangue",
                    models.CharField(
                        blank=True,
                        help_text="Tipo sanguineo do paciente",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "acompanhante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acompanhantes.acompanhante",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicos.medico",
                    ),
                ),
            ],
        ),
    ]
