# Generated by Django 4.1.1 on 2023-04-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="acompanhante",
        ),
    ]
