# Generated by Django 4.1.7 on 2023-04-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="data_hora_entrada",
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paciente",
            name="data_hora_saida",
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
