# Generated by Django 4.1.7 on 2023-04-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_paciente_data_hora_entrada_paciente_data_hora_saida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="data_hora_entrada",
            field=models.DateTimeField(help_text="Data e hora de entrada"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="data_hora_saida",
            field=models.DateTimeField(
                blank=True, help_text="Data e hora de saida", null=True
            ),
        ),
    ]
