# Generated by Django 4.1.7 on 2023-04-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0003_alter_paciente_data_hora_entrada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="idade",
            field=models.IntegerField(
                help_text="Idade do funcionário (apenas numeros)", max_length=3
            ),
        ),
    ]
