# Generated by Django 4.1.7 on 2023-04-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(help_text="Nome do medico", max_length=30)),
                (
                    "sobrenome",
                    models.CharField(help_text="Sobrenome do medico", max_length=200),
                ),
                ("crm", models.CharField(help_text="CRM do médico", max_length=20)),
                (
                    "area_atuacao",
                    models.CharField(help_text="Área de atuação", max_length=60),
                ),
            ],
        ),
    ]
